title: Rodrigo Lugo
email: rlugog96@gmail.com
description: >- 
  Data Analyst Portfolio – Python, SQL, Tableau | Turning data into insights
theme: jekyll-theme-minimal
github_username: rlugog
linkedin: https://www.linkedin.com/in/rodrigolugo-dataanalyst
